version: "3.8"
services:
  front:
    build:
      context: ./frontend
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - client_node_modules:/app/node_modules
    networks:
      wecall_net:
        ipv4_address: $CLIENT_IP

  server:
    build: ./reservation_system
    tty: true
    ports:
      - 3000:3000
      # appが更新されたら、コンテナ起動時にreservation_systemが更新される
    volumes:
      - ./reservation_system:/app
    networks:
      wecall_net:
        ipv4_address: $SERVER_IP
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    volumes:
      # - ../mysql/init.d:/docker-entrypoint-initdb.d
      # /var/lib/mysqlが更新されたら、コンテナ起動時に./dab/dataが更新される
      - "./db/data:/var/lib/mysql"
    networks:
      wecall_net:
        ipv4_address: $DB_HOST
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      #MYSQL_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    hostname: $DB_HOSTNAME
    restart: always
    user: $DB_USER

volumes:
  client_node_modules:

networks:
  wecall_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $SUBNET