version: "3.8"
services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./reservation_system:/app
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    depends_on: 
      - db
  db:
    image: mysql:8.3.0
    ports:
      - 5432:5432
    volumes:
      - ../mysql/init.d:/docker-entrypoint-initdb.d
      - ../mysql/pgdata:/var/lib/postgresql/data
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    hostname: $DB_HOSTNAME
    restart: always
    user: $DB_USER
