version: '3.8'
services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ../postgres/init.d:/docker-entrypoint-initdb.d
      - ../postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    hostname: ${DB_HOSTNAME}
    restart: always
    user: ${DB_USER}
